### ISSUE TITLE
Running with Limited Numbers of Features

### ISSUE THREAD

**Issue by delucalab** [ComputationalProteomics/NormalyzerDE#23]
My apologies in advance for the naive question. I am trying to use the normalyzer R package for a dataset that has less than 50 features. I changed the tiny run threshold but receive the following error: 

"This function is worried that the number of rows in the data matrix, 30, is too small for reliable estimation of the vsn transformation parameters. If you think that your data really have more rows, then please check whether there is a data transmission problem (e.g., matrix transposition?). Otherwise, if you are sure about what you are doing, you can change the parameter 'minDataPointsPerStratum' in order to reduce the minimal number of rows acceptable for proceeding."

How can I change the 'minDataPointsPerStratum' parameter or can I skip VSN transformation and just compare the other methods since it wouldn't be suitable with the number of features I have?

Any advice or help would be much appreciated.

**Comment by Jakob37** [comment]
Hi! Thank you for your comment.

I think the size of your data means that you will need to do a 'tiny run', meaning that it will skip the parts of the analysis which would require a larger size of data points (i.e. normalizations such as VSN would be unreliable). If you leave the 'tinyRunThes' as it is, does it run through successfully with a partial report? If else, you could try increasing it to more than the size of your dataset and see what it gives.

If reducing the threshold to a lower value I would expect things to crash, because then this smaller dataset will be sent to normalizations that are not built to handle dataset of such size. I would guess that this is what happened in your case.

Not sure if I managed to address your question. If not, feel free to follow up with more comments. I will try keeping a closer eye on the GitHub the coming week and come back to you quicker.

**Comment by delucalab** [comment]
Thanks! I was able to get a 'tiny run' where the following normalization methods were run: log2, GI, median, mean, quantile, CycLoess, and RLR. However, I was hoping that I could still see information like PCV, PMAD, PEV, correlation plots, etc for the normalization methods that could be run on the smaller datasets. Do all those metrics also require more features or could I somehow get that information to output with a 'tiny run'?

**Comment by Jakob37** [comment]
I see! I think generating the data used in these tended to crash NormalyzerDE in different stages for smaller datasets, and that is why they are not included. So right now I do unfortunately think that they cannot easily be accessed for a tiny dataset. I will take a look ahead though and see if there would be any good way to include these without risking making NormalyzerDE unstable. Thanks for raising the points!
