### ISSUE TITLE
Values of 0.0 throw an error

### ISSUE THREAD

**Issue by arnscott** [ComputationalProteomics/NormalyzerDE#8]
If 0.0 values are in the dataset, the following error is thrown:

Error in verifyValidNumbers(dataMatrix, groups, noLogTransform = noLogTransform,  : 
  Encountered below-one values in raw data. As the data is log-transformed 
during processing this will lead to negative values which in turn will 
crash processing. Consider using the 'noLogTransform' option if your data 
already is normally distributed or scaling all values if appropriate.

I know there was a regex fix in the works, but not sure if its in the main version. I just installed the new version via devtools and am running 1.1.12.

A work around is to just change all the 0.0's to 0's using sed and then running, but it could help some users to detect it!

**Comment by Jakob37** [comment]
For now I have decided to not allow decimal zeroes in the input, but thanks your input I have added a clear input parsing message pointing to the unwanted fields.

**Comment by zangtqut** [comment]
I got same error, but I have checked my data, there is no 0.0 value. The error is below, do I have too many NA?
Error in verifyValidNumbers(dataMatrix, groups, noLogTransform = noLogTransform, :
Encountered below-one values in raw data. As the data is log-transformed
during processing this will lead to negative values which in turn will
crash processing. Consider using the 'noLogTransform' option if your data
already is normally distributed or scaling all values if appropriate.
First ten row numbers where this issue was encountered, excluding header row:
21, 24, 36, 81, 377, 386, 578, 585, 612, 645
Content of first row (row 21) with issues:
0.992689, 3.74415, 1.81042, NA, 1.00965, NA, 1.30929, 0.865609, NA, 5.44219, NA, NA, NA, 1.59918, NA, NA, 3.77943, 6.19949, NA, 2.41279, NA, NA, NA, NA, 2.84135, NA, NA, NA, 18.0157, 12.0897, 26.6993, 40.1254, NA, NA, 0.977377, 3.30268, NA, NA, 3.01623, NA, NA, 1.80722, 1.08633, NA, NA, NA, NA, NA, 1.93425, 9.85014, NA, NA, NA, NA, 1.40683, NA, NA, 2.63114, 2.23639, NA, NA, NA, NA, NA, NA, NA, 5.95185, 4.51903, NA, NA, NA, NA, NA, NA, 5.88965

**Comment by Jakob37** [comment]
Hi @zangtqut 

I think it is complaining about that you have below-one values (0.865609 for instance). This probably means that your data already is log transformed, and should be run with the 'noLogTransform' option. Otherwise, it will log transform it again, which will yield negative values.

**Comment by zangtqut** [comment]
Thank you Jakob, I'll have a check on it.

**Comment by zangtqut** [comment]
Hello,

Thank you very much for the reply. I have checked the data processing software, which is a new one for us. Even I turned off the cross-run normalization, there are still values <1. I think it's the new algorithm. I'm using the browser version of NormalyzerDE, is there a way to turn off the log transfer formation or any way to avoid it (like replace all values<1 to 1)?

Kind regards

Zang

Tuo Zang, PhD|MSc|BSc(Hons)
Post-doctoral Research Fellow, Burns and Trauma Research,
School of Biomedical Sciences, Queensland University of Technology,
Tissue Repair and Translational Physiology Program, Institute of Health and Biomedical Innovation (IHBI),
Centre for Children’s Health Research (CCHR), Level 8, 62 Graham St, South Brisbane, Australia, 4101
Email: ***@***.******@***.***> | Ph: +61730697776

________________________________

**Comment by Jakob37** [comment]
> Hello, Thank you very much for the reply. I have checked the data processing software, which is a new one for us. Even I turned off the cross-run normalization, there are still values <1. I think it's the new algorithm. I'm using the browser version of NormalyzerDE, is there a way to turn off the log transfer formation or any way to avoid it (like replace all values<1 to 1)? Kind regards

Hi again,

I would say it is important here to understand what initial processing the software you are using are doing to the data, such that you don't end up with 'double normalization'. But if it only log transforms the data, then you could click the option 'Data already log normalized' under advanced settings in the web interface, as shown in the picture below:

![Screenshot from 2021-12-02 08-32-23](https://user-images.githubusercontent.com/7374399/144377606-13c4a66c-adc1-4a2e-a6d3-6cf6c3ac26b3.png)

**Comment by zangtqut** [comment]
Hello,

Thank you so much for this. This is very helpful, very appreciate your time.

Kind regards

Zang

Tuo Zang, PhD|MSc|BSc(Hons)
Post-doctoral Research Fellow, Burns and Trauma Research,
School of Biomedical Sciences, Queensland University of Technology,
Tissue Repair and Translational Physiology Program, Institute of Health and Biomedical Innovation (IHBI),
Centre for Children’s Health Research (CCHR), Level 8, 62 Graham St, South Brisbane, Australia, 4101
Email: ***@***.******@***.***> | Ph: +61730697776

________________________________
